
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.JToggleButton;


public class InterfaceGrafica extends javax.swing.JFrame {

    private JToggleButton btn1;
    private JScrollPane jScrollPane1;
    JTextPane t1;
    private JScrollPane jScrollPane2;
    private JTextPane t2;
    private JScrollPane jScrollPane3;
    private JTextPane t4;
    private JScrollPane jScrollPane4;
    private JTextPane t7;
    private JScrollPane jScrollPane5;
    private JTextPane t5;
    private JScrollPane jScrollPane6;
    private JTextPane t3;
    private JScrollPane jScrollPane7;
    private JTextPane t8;
    private JScrollPane jScrollPane8;
    private JTextPane t9;
    private JScrollPane jScrollPane9;
    private JTextPane t6;
    private JButton jButton1;
    private int cont = 0;
    private JTextPane nnos;
    private Component jLabel3;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JScrollPane jScrollPane10;
    private JScrollPane jScrollPane11;
    private JTextPane profundidade;
    private JLabel jLabel4;
    private JScrollPane jScrollPane12;
    private Object res;
    private Component jScrollPane13;
    private JTextField xtexto;
    private int tbusca;
    private JToggleButton btn;
    private JToggleButton buscaestrela;
    private JButton jButton2;
    

    /**
     * Creates new form NewJFrame
     */
    public InterfaceGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        t4 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        t7 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        t5 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        t8 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        t9 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        t6 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        nnos = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        profundidade = new javax.swing.JTextPane();
        xtexto = new javax.swing.JTextField();
        btn = new javax.swing.JToggleButton();
        buscaestrela = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setText("Busca Largura");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn1MousePressed(evt);
            }
        });

        jScrollPane1.setViewportView(t1);

        jScrollPane2.setViewportView(t2);

        jScrollPane3.setViewportView(t4);

        jScrollPane4.setViewportView(t7);

        jScrollPane5.setViewportView(t5);

        jScrollPane6.setViewportView(t3);

        jScrollPane7.setViewportView(t8);

        jScrollPane8.setViewportView(t9);

        jScrollPane9.setViewportView(t6);

        jButton1.setText("Passos");
        jButton1.setEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText("Insira uma configuração inicial Caso não insira sera carregado automaticamente ");

        jLabel2.setText("Numero de No(s) Expandidos ");

        jScrollPane10.setViewportView(nnos);

        jLabel4.setText("Profundidade");

        profundidade.setText("7");
        jScrollPane12.setViewportView(profundidade);

        xtexto.setEditable(false);
        xtexto.setText("         Agurdando Comondos");

        btn.setText("Buscar em Profundidade");
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMousePressed(evt);
            }
        });

        buscaestrela.setText("Busca A*");
        buscaestrela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaestrelaActionPerformed(evt);
            }
        });

        jButton2.setText("Busca Gulosa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(xtexto)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn1)
                                    .addComponent(buscaestrela))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jButton1))))
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane10)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane6)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(8, 8, 8)))
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscaestrela)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xtexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Inicio evente busca em largura
    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        // TODO add your handling code here:
        tbusca=1;
        xtexto.setText("Iniciando busca em largura");
        int estadoInicial[][] = {{4, 1, 3},
        {0, 2, 6},
        {7, 5, 8}};//{{1,2,3},{4,5,0},{7,8,6}};//{{7,2,4},{5,0,6},{8,3,1}};
        if (pegadadosTela() != null) {
            estadoInicial = pegadadosTela();
        }
        Estado e = new Estado(estadoInicial);

        No noInicial = new No(e, 0, -1);
        BuscaLargura busca = new BuscaLargura();
        BuscaLargura.setNumerodeNos(0);
        cont = 0;
        if (busca.Busca(noInicial, Integer.valueOf(profundidade.getText()))) {
            jButton1.setEnabled(true);
            xtexto.setText("Busca em Largura Realizada Com Sucesso");
            
        } else {
            xtexto.setText("busca não Enscontrou solução tente aumentar a profundidade");
        }
        nnos.setText(String.valueOf(BuscaLargura.numerodeNos));

    }//GEN-LAST:event_btn1MouseClicked
//fim busca em largura
    
 //incio botão para navegar no caminho retornado pela busca
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(tbusca==1){
        if (jButton1.isEnabled()) {
            prenchertela(BuscaLargura.caminho.get(cont).getEstado().getMatriz());
        }
        if (BuscaLargura.caminho.get(cont).getEstado().Objetivo(BuscaLargura.caminho.get(cont).getEstado().getMatriz())) {
            jButton1.setEnabled(false);
        }
        }else if(tbusca==3){
            if(jButton1.isEnabled()){
                prenchertela(AEstrela.Caminho.get(cont).getEstado().getMatriz());
            }
            if(AEstrela.Caminho.get(cont).getEstado().Objetivo(AEstrela.Caminho.get(cont).getEstado().getMatriz())){
                jButton1.setEnabled(false);
            }
        }
        else if(tbusca==4){
            if(jButton1.isEnabled()){
                prenchertela(BuscaGulosa.Caminho.get(cont).getEstado().getMatriz());
            }
            if(BuscaGulosa.Caminho.get(cont).getEstado().Objetivo(BuscaGulosa.Caminho.get(cont).getEstado().getMatriz())){
                jButton1.setEnabled(false);
            }
        }
        else{
            nnos.setText(String.valueOf(BuscaProfundidade.NumerodeNos));
            if (jButton1.isEnabled()) {
            prenchertela(BuscaProfundidade.caminho.get(cont).getEstado().getMatriz());
        }
        if (BuscaProfundidade.caminho.get(cont).getEstado().Objetivo(BuscaProfundidade.caminho.get(cont).getEstado().getMatriz())) {
            jButton1.setEnabled(false);
            
        }
       
        }
        
         cont++;          

    }//GEN-LAST:event_jButton1MouseClicked

    private void btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseClicked
        // TODO add your handling code here:
      
        BuscaProfundidade.setNumerodeNos(0);
        int estadoInicial[][] = {{4, 1, 3},
        {0, 2, 6},
        {7, 5, 8}};//{{1,2,3},{4,5,0},{7,8,6}};//{{7,2,4},{5,0,6},{8,3,1}};
       
        if (pegadadosTela() != null) {
            estadoInicial = pegadadosTela();
        }
        Estado e = new Estado(estadoInicial);

        No noInicial = new No(e, 0, -1);
        BuscaProfundidade busca = new BuscaProfundidade();
        BuscaProfundidade.setNumerodeNos(0);
        cont = 0;
        xtexto.setText("Iniciando busca em Profundidade");
        if (busca.Busca(noInicial, Integer.valueOf(profundidade.getText()))) {
            jButton1.setEnabled(true);
            xtexto.setText("Busca em Profundidade Realizada Com Sucesso");
           
        } else {
            xtexto.setText("busca não Enscontrou solução tente aumentar a profundidade");
        }
         nnos.setText(String.valueOf(BuscaLargura.numerodeNos));

    }//GEN-LAST:event_btnMouseClicked

    private void btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MousePressed
        // TODO add your handling code here:
        xtexto.setText("Realizando busca");
    }//GEN-LAST:event_btn1MousePressed

    private void btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMousePressed
        // TODO add your handling code here:
        xtexto.setText("Realizando busca");
    }//GEN-LAST:event_btnMousePressed

    private void buscaestrelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaestrelaActionPerformed
        // TODO add your handling code here:
        tbusca=3;
        int estadoInicial[][] = {{4, 1, 3},
        {0, 2, 6},
        {7, 5, 8}};//{{1,2,3},{4,5,0},{7,8,6}};//{{7,2,4},{5,0,6},{8,3,1}};
       
        if (pegadadosTela() != null) {
            estadoInicial = pegadadosTela();
        }
        Estado e = new Estado(estadoInicial);

        No noInicial = new No(e, 0, -1);
        AEstrela busca = new AEstrela();
        AEstrela.setNumerodeNos(0);
        cont = 0;
        xtexto.setText("Iniciando busca em A*");
        if (busca.Busca(noInicial, Integer.valueOf(profundidade.getText()))) {
            jButton1.setEnabled(true);
            xtexto.setText("Busca em A* Realizada Com Sucesso");
           
        } else {
            xtexto.setText("busca não Enscontrou solução tente aumentar a profundidade");
        }
         nnos.setText(String.valueOf(AEstrela.numerodeNos));

                                    
    }//GEN-LAST:event_buscaestrelaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        tbusca=4;
        int estadoInicial[][] = {{4, 1, 3},
        {0, 2, 6},
        {7, 5, 8}};//{{1,2,3},{4,5,0},{7,8,6}};//{{7,2,4},{5,0,6},{8,3,1}};
       
        if (pegadadosTela() != null) {
            estadoInicial = pegadadosTela();
        }
        Estado e = new Estado(estadoInicial);

        NoBuscaGulosa noInicial = new NoBuscaGulosa(e, 0, -1);
        BuscaGulosa busca = new BuscaGulosa();
        busca.setNumerodeNos(0);
        cont = 0;
        xtexto.setText("Iniciando busca Busca Gulosa ");
        if (busca.Busca(noInicial, Integer.valueOf(profundidade.getText()))) {
            jButton1.setEnabled(true);
            xtexto.setText("Busca Gulosa Realizada Com Sucesso");
           
        } else {
            xtexto.setText("busca não Enscontrou solução tente aumentar a profundidade");
        }
         nnos.setText(String.valueOf(busca.numerodeNos));

                                    
                 
    }//GEN-LAST:event_jButton2ActionPerformed
    public void prenchertela(int mat[][]) {
        t1.setText(String.valueOf(mat[0][0]));
        t2.setText(String.valueOf(mat[0][1]));
        t3.setText(String.valueOf(mat[0][2]));
        t4.setText(String.valueOf(mat[1][0]));
        t5.setText(String.valueOf(mat[1][1]));
        t6.setText(String.valueOf(mat[1][2]));
        t7.setText(String.valueOf(mat[2][0]));
        t8.setText(String.valueOf(mat[2][1]));
        t9.setText(String.valueOf(mat[2][2]));

    }

    public int[][] pegadadosTela() {
        int[][] mat = new int[3][3];
        if ((!t1.getText().isEmpty()) && (!t2.getText().isEmpty())
                && (!t3.getText().isEmpty()) && (!t4.getText().isEmpty())
                && (!t5.getText().isEmpty()) && (!t6.getText().isEmpty())
                && (!t7.getText().isEmpty()) && (!t8.getText().isEmpty())
                && (!t9.getText().isEmpty())) {
            mat[0][0] = Integer.valueOf(t1.getText());
            mat[0][1] = Integer.valueOf(t2.getText());
            mat[0][2] = Integer.valueOf(t3.getText());
            mat[1][0] = Integer.valueOf(t4.getText());
            mat[1][1] = Integer.valueOf(t5.getText());
            mat[1][2] = Integer.valueOf(t6.getText());
            mat[2][0] = Integer.valueOf(t7.getText());
            mat[2][1] = Integer.valueOf(t8.getText());
            mat[2][2] = Integer.valueOf(t9.getText());
            return mat;

        }

        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGrafica().setVisible(true);
            }

        });
    }

    private static class jScrollPane13 {

        public jScrollPane13() {
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn;
    private javax.swing.JToggleButton btn1;
    private javax.swing.JToggleButton buscaestrela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane nnos;
    private javax.swing.JTextPane profundidade;
    public static javax.swing.JTextPane t1;
    public javax.swing.JTextPane t2;
    private javax.swing.JTextPane t3;
    private javax.swing.JTextPane t4;
    private javax.swing.JTextPane t5;
    private javax.swing.JTextPane t6;
    private javax.swing.JTextPane t7;
    private javax.swing.JTextPane t8;
    private javax.swing.JTextPane t9;
    private javax.swing.JTextField xtexto;
    // End of variables declaration//GEN-END:variables

